//file:noinspection GrUnresolvedAccess

import groovy.json.JsonSlurper
import java.nio.file.FileVisitResult
import java.nio.file.Path
import java.nio.file.SimpleFileVisitor
import java.nio.file.attribute.BasicFileAttributes

import static groovy.json.JsonOutput.toJson
import static java.nio.file.FileSystems.newFileSystem
import static java.nio.file.Files.copy
import static java.nio.file.Files.createDirectories
import static java.nio.file.Files.deleteIfExists
import static java.nio.file.Files.isRegularFile
import static java.nio.file.Files.walk
import static java.nio.file.Files.walkFileTree
import static java.nio.file.Path.of as pathOf
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING
import static java.util.regex.Pattern.compile
import static java.util.stream.Collectors.toUnmodifiableSet
import static java.util.stream.Stream.concat as concatStreams
import static javax.imageio.ImageIO.read as readImage

plugins {
    id 'java'
    id 'io.papermc.paperweight.userdev' version "${paperweight_version}"
    id 'net.minecrell.plugin-yml.paper' version "${paper_plugin_yml_version}"
    id 'xyz.jpenilla.run-paper' version "${run_paper_version}"
}

group = 'me.supcheg'
version = '1.0.1'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://repo.papermc.io/repository/maven-public' }
    maven { url 'https://libraries.minecraft.net' }
    maven { url 'https://repo.codemc.io/repository/maven-public' }
}

dependencies {
    paperweight.paperDevBundle "${minecraft_version}-R0.1-SNAPSHOT"
    compileOnly "org.popcraft:chunky-common:${chunky_version}"
    compileOnly "org.popcraft:chunky-bukkit:${chunky_version}"
    compileOnly "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "com.google.dagger:dagger-compiler:${dagger_version}"

    library "org.javassist:javassist:${javaassist_version}"
    library "com.google.dagger:dagger:${dagger_version}"

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation "org.mockito:mockito-core:${mockito_version}"
    testImplementation "com.github.seeseemelk:MockBukkit-v${minecraft_api_version}:${mock_bukkit_version}"
    testCompileOnly "org.projectlombok:lombok:${lombok_version}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok_version}"

    testImplementation "org.spongepowered:configurate-yaml:${configurate_yaml_version}"
    testImplementation "io.papermc.paper:paper-mojangapi:${minecraft_version}-R0.1-SNAPSHOT"
}

configurations {
    testImplementation {
        exclude group: 'io.papermc.paper', module: 'paper-server'
    }
}

test {
    useJUnitPlatform()
}

runServer {
    minecraftVersion "${minecraft_version}"
    jvmArgs = [
            '-Xms1G', '-Xmx2G',
            '-XX:+UseG1GC', '-XX:+ParallelRefProcEnabled', '-XX:MaxGCPauseMillis=200',
            '-XX:+UnlockExperimentalVMOptions', '-XX:+DisableExplicitGC', '-XX:+AlwaysPreTouch',
            '-XX:G1NewSizePercent=30', '-XX:G1MaxNewSizePercent=40', '-XX:G1HeapRegionSize=8M',
            '-XX:G1ReservePercent=20', '-XX:G1HeapWastePercent=5', '-XX:G1MixedGCCountTarget=4',
            '-XX:InitiatingHeapOccupancyPercent=15', '-XX:G1MixedGCLiveThresholdPercent=90',
            '-XX:G1RSetUpdatingPauseTimePercent=5', '-XX:SurvivorRatio=32', '-XX:+PerfDisableSharedMem',
            '-XX:MaxTenuringThreshold=1', '-Dusing.aikars.flags=https://mcflags.emc.gs', '-Daikars.new.flags=true'
    ]
    if (file("${path}/log4j2.xml").exists()) jvmArgs += "-Dlog4j.configuration=${path}/log4j2.xml"
}

paper {
    name = 'AdvancedManHunt'
    version = "${project.version}"
    description = 'Running multiple ManHunt games on the same server at once'
    website = 'https://github.com/Pupcheg/AdvancedManHunt'
    author = 'Supcheg'

    main = 'me.supcheg.advancedmanhunt.paper.PaperPlugin'
    bootstrapper = 'me.supcheg.advancedmanhunt.paper.InjectorBootstrap'
    loader = 'me.supcheg.advancedmanhunt.paper.ConfigLibraryResolver'
    generateLibrariesJson = true

    apiVersion = "${minecraft_api_version}"

    serverDependencies {
        'Chunky' {
            required = false
            load = 'BEFORE'
        }
    }

    permissions {
        'advancedmanhunt.notifications' {
            setDefault('OP')
        }
        'advancedmanhunt.game.configure_any' {
            setDefault('OP')
        }
        'advancedmanhunt.debug' {
            setDefault('OP')
        }
    }
}

//<editor-fold desc="task:checkTranslationKeysUses" defaultstate="collapsed">
tasks.register('checkTranslationKeysUses') {
    def keyFinder = compile '(?:key|translatable)\\("([A-z._]+)"|<lang:([A-z._]*):?.*>'

    def usedKeys = concatStreams(
            walk(file('src/main/java').toPath()),
            walk(file('src/main/resources').toPath())
                    .filter { it.toString().endsWith('.json') }
    )
            .filter { isRegularFile(it) }
            .map { it.text }
            .map { keyFinder.matcher(it) }
            .flatMap { it.results() }
            .map { it.group(1) != null ? it.group(1) : it.group(2) }
            .collect toUnmodifiableSet()

    file('resourcepack/advancedmanhunt/lang').eachFile { def file ->
        def json = new JsonSlurper().parseText(file.text) as Map<String, Object>
        def allKeys = json.keySet()

        if (allKeys != usedKeys) {
            def notUsed = allKeys.toSet()
            notUsed.removeAll(usedKeys)

            def notDefined = usedKeys.toSet()
            notDefined.removeAll(allKeys)

            throw new IllegalStateException("Not used: ${notUsed}. Not defined: ${notDefined}")
        }
    }
}
//</editor-fold>

compileJava {
    dependsOn checkTranslationKeysUses
}

//<editor-fold desc="task:generateResourcePack" defaultstate="collapsed">
tasks.register('generateResourcePack') {
    def namespace = rootProject.name.toLowerCase()

    def resourcepackDir = file('resourcepack').toPath()

    def assets = new JsonSlurper().parse resourcepackDir.resolve('assets.json')

    def outFile = layout.buildDirectory.get().asFile.toPath().resolve "libs/${namespace}.zip"
    deleteIfExists outFile
    createDirectories outFile.parent

    newFileSystem(outFile, ['create': true]).withCloseable { def fs ->
        def assetsDir = fs.getPath 'assets'
        def itemModels = assetsDir.resolve "${namespace}/models/item"
        def itemTextures = assetsDir.resolve "${namespace}/textures/item"
        def guiTextures = assetsDir.resolve "${namespace}/textures/gui"
        def guiFont = assetsDir.resolve "${namespace}/font/gui.json"
        def paper = assetsDir.resolve 'minecraft/models/item/paper.json'
        def defaultFont = assetsDir.resolve 'minecraft/font/default.json'
        def langDir = assetsDir.resolve "${namespace}/lang"

        def paperJson = [
                'parent'   : 'minecraft:item/generated',
                'textures' : [
                        'layer0': 'minecraft:item/paper'
                ],
                'overrides': []
        ]
        def guis = [
                'providers': []
        ]

        def resources = [
                'buttons': [],
                'guis'   : []
        ]

        createDirectories itemModels
        createDirectories itemTextures

        createDirectories guiTextures
        createDirectories paper.parent
        createDirectories guiFont.parent
        createDirectories defaultFont.parent
        createDirectories langDir

        def curModel = 0
        def curChar = 1

        def rootDir = resourcepackDir.resolve assets['root'] as String

        assets['item'].each { def item ->
            def assetPath = rootDir.resolve item as String
            def customModelData = 2500 + curModel

            var image = readImage assetPath.toFile()

            itemModels.resolve("${curModel}.json").write toJson([
                    'parent'  : 'minecraft:item/generated',
                    'textures': [
                            'layer0': "${namespace}:item/${curModel}"
                    ]
            ])

            copy assetPath, itemTextures.resolve("${curModel}.png")

            paperJson['overrides'] += [
                    'model'    : "${namespace}:item/${curModel}",
                    'predicate': [
                            'custom_model_data': customModelData
                    ]
            ]

            resources['buttons'] += [
                    'path'             : "${namespace}/${item}",
                    'custom_model_data': customModelData,
                    'height'           : image.height,
                    'width'            : image.width
            ]

            curModel++
        }

        assets['char'].each { def aChar ->
            def assetPath = rootDir.resolve aChar as String

            var image = readImage assetPath.toFile()

            guis['providers'] += [
                    'type'  : 'bitmap',
                    'file'  : "${namespace}:gui/${curChar}.png",
                    'ascent': 13,
                    'height': image.height,
                    'chars' : [curChar as char]
            ]
            copy assetPath, guiTextures.resolve("${curChar}.png")

            resources['guis'] += [
                    'path'    : "${namespace}/${aChar}",
                    'font'    : "${namespace}:gui",
                    'alt_char': "${curChar as char}",
                    'height'  : image.height,
                    'width'   : image.width
            ]

            curChar++
        }

        assets['lang'].each { def lang ->
            def assetPath = rootDir.resolve lang as String
            copy assetPath, langDir.resolve(assetPath.getFileName() as String)
        }

        guiFont.write toJson(guis)
        paper.write toJson(paperJson)

        defaultFont.write '{"providers":[{"type":"space","advances":{"\uF808":-8}}]}'
        copy resourcepackDir.resolve(assets['meta'] as String), fs.getPath('pack.mcmeta')


        def resourcesJson = layout.buildDirectory.get().asFile.toPath().resolve 'resources/main/resources.json'
        createDirectories resourcesJson.parent
        resourcesJson.write toJson(resources)

        if (project.hasProperty 'copyResourcepack') { // -PcopyResourcepack
            def dest = pathOf project.properties['copyResourcepack'] as String
            def unzip = project.hasProperty 'unzipResourcepack'

            createDirectories dest.parent
            dest.deleteDir()
            if (unzip) {
                def zip = fs.getPath('')
                walkFileTree zip, new Win2ZipCopyFileVisitor(zip, dest)
                println "Unziped resourcepack to ${dest}"
            } else {
                copy outFile, dest, REPLACE_EXISTING
                println "Copied resourcepack to ${dest}"
            }
        }
    }
}

class Win2ZipCopyFileVisitor extends SimpleFileVisitor<Path> {
    Path targetPath
    Path sourcePath
    boolean firstDirectory = true

    Win2ZipCopyFileVisitor(sourcePath, targetPath) {
        this.sourcePath = sourcePath
        this.targetPath = targetPath
    }

    @Override
    FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
        if (firstDirectory) {
            firstDirectory = false
        } else {
            createDirectories resolveDestFile(dir)
        }
        return FileVisitResult.CONTINUE
    }

    @Override
    FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
        def dest = resolveDestFile file
        createDirectories dest.parent
        copy file, dest, REPLACE_EXISTING
        return FileVisitResult.CONTINUE
    }

    private Path resolveDestFile(Path file) {
        return targetPath.resolve(sourcePath.resolve(file as String) as String)
    }
}
//</editor-fold>

jar {
    dependsOn generateResourcePack
    finalizedBy reobfJar
}

java {
    sourceCompatibility JavaVersion.toVersion(java_version)
    targetCompatibility JavaVersion.toVersion(java_version)
}

tasks.withType(JavaCompile).configureEach {
    options.release.set java_version as int
    options.encoding 'UTF-8'
    sourceCompatibility java_version
    targetCompatibility java_version
}
