java_version=21
# gradle plugins
paperweight_version=1.5.15
paper_plugin_yml_version=0.6.0
bukkit_plugin_yml_version=0.6.0
run_paper_version=2.2.3
# minecraft
minecraft_version=1.20.4
minecraft_api_version=1.20
# dependencies
chunky_version=1.3.143
lombok_version=1.18.32
javaassist_version=3.30.2-GA
dagger_version=2.51.1
# test
junit_version=5.10.2
mockito_version=5.11.0
mock_bukkit_version=3.80.0
slf4j_simple_version=2.0.12
configurate_yaml_version=4.2.0-SNAPSHOT
