region:
  max_regions_per_world: 2
template_load:
  thread_pool_size: 4
  empty_template_warning: true
game:
  safe_leave:
    enable: true
    enable_after: 30s
    return_duration: 5m
  player_returner:
    type: teleport
    argument: world[spawn]
  portal:
    nether_multiplier: 8
    overworld_safe_zone: 192b
    nether_safe_zone: 192b
  config_defaults:
    max_hunters: 5
    max_spectators: 15
    randomize_roles_on_start: true
    overworld_template: default_overworld
    nether_template: default_nether
    end_template: default_end
  config_limits:
    max_hunters: 1-5
    max_spectators: 0-30