region:
  max_regions_per_world: 2
  max_worlds_per_environment: 1
template_load:
  thread_pool_size: 4
  empty_template_warning: true
serialization:
  compact_coords: true
game:
  safe_leave:
    enable: true
    enable_after: 30s
    return_duration: 5m
  player_returner:
    type: teleport
    argument: world[spawn]