name: gradle-ci

on: [ push ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Injector
        run: ./gradlew :injector:build

      - name: Build AdvancedManHunt
        run: ./gradlew build --scan

      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/libs/*.jar
