name: gradle-ci

on: [ push ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Initialize caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-snapshot-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-snapshot-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Injector
        run: ./gradlew :injector:build

      - name: Build AdvancedManHunt
        run: ./gradlew build --scan

      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            injector/build/libs/*.jar
